/* ------------------------------------------------------------------------- */
/*
  Title: NNCode, Neural Network execution code.
  Automatically generated by SNN, Thu Apr 20 09:36:30 2023


  License Agreement:
  -----------------

  Copyright StatSoft Inc., 2000-2001, all rights reserved.
  This source code (Source Code Generated by STATISTICA Neural Networks,
  referred to as "CG" below) is owned by StatSoft Inc. and is protected
  by United States Copyright laws and international treaty provisions. You
  shall treat the CG like any copyrighted material.
  The CG may not be redistributed or used except in accordance with the
  conditions below.

  The licensee is granted a license to incorporate the CG as embedded
  software in their own hardware and software products, and to distribute an
  unlimited number of such embedded copies as part of this license subject to
  obtaining prior written consent from StatSoft Inc., and subject to
  the conditions listed below.

  Prior consent is required so that StatSoft Inc. can ensure that license
  conditions are not breached, and can track legitimate use of the CG. Consent
  shall not be refused unless StatSoft Inc. reasonably believes that a
  breach of license conditions will occur. Consent shall usually be granted
  within five working days of the request, providing that sufficient details of
  the intended use are given.

  Requests should be sent to SNN Project Director, StatSoft, Inc.,
  2300 East 14th Street, Tulsa OK 74104 USA, FAX: 918-749-2217,
  E-Mail: info@statsoft.com.

  The licensee may modify the CG as they see fit for embedded use, including
  recoding into alternative programming languages, altering the neural network
  architecture and weights, and otherwise modifying the CG, provided that they
  keep intact this copyright and license notice.

  The licensee may distribute products including the compiled version of CG.

  The licensee shall not:-
    Sublicense, rent, lease, or assign any portion of the CG to third parties.
    Allow compiled versions of the CG to be incorporated in products owned
    by third parties.
    Allow access to the CG to third parties.
    Use (implicitly or explicitly) any reference to StatSoft, Inc., STATISTICA,
    STATISTICA Neural Networks, or any trade names used by StatSoft, Inc.
    to describe, promote, or reference products in which CG is used, or which
    benefit from CG.

  Except as expressly stated herein, the CG is provided "AS IS." The licensee
  shall be entirely responsible for the selection of the CG and for the
  installation, integration, use of, and results obtained from, the CG.
  In particular, but without limitation, attention is drawn to the issue of
  "limited numeric accuracy," which implies that results may not be identical to
  those when executing the same network in STATISTICA Neural Networks or through
  its Application Programming Interface.

  All other warranties or conditions, either express or implied, including but
  not limited to implied warranties of merchantability or fitness for a
  particular purpose, with respect to the CG and written information
  accompanying the CG, are excluded from the license.

  No liability for Consequential Damages. To the maximum extent permitted by
  applicable law, in no event shall StatSoft Inc.,
  or the vendor be liable for any damages whatsoever
  (including, without limitation, damages for loss of profits,
  business interruption, loss of information, or any other pecuniary loss)
  arising out of the use or inability to use this product,
  even if the vendor has been advised of the possibility of
  such damages.

  This license and your right to use the CG shall terminate automatically
  if StatSoft, Inc. determines that you violate any part of the agreement
  or if you violate any part of this agreement without the knowledge of
  StatSoft, Inc. In the event of termination, you shall immediately destroy
  all copies of the CG.

  This agreement constitutes the entire agreement between you and StatSoft Inc.,
  and supersedes any prior agreement concerning the CG. It shall
  not be modified except by written agreement dated subsequent to the date of
  this agreement signed by an authorized representative of StatSoft Inc.
  StatSoft Inc. shall not be bound by any provision of any purchase order,
  confirmation, correspondence, or otherwise, unless StatSoft Inc.
  specifically agrees to the provision in writing.

  This agreement shall be considered as a contract made in the United States
  of America and according to United States Law,
  subject to the exclusive jurisdiction of the United States Courts.
*/
/* standard includes. math.h needed for exp() function. */

#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>

#ifndef FALSE
#define FALSE 0
#define TRUE 1
#endif

#define MENUCODE -999


static double NNCode04Thresholds[] =
{

/* layer 1 */
0.034276133546116416, 0.48928827678711673, 0.67455165839230902, 0.52107651860987392,
0.83946056565353366, -0.019968492896301062, -0.51184614713409238, 0.28550665401295539,
0.4253317881414746, 0.4625887934686892, 0.12266351184697059, -0.38081254328802772,
-0.47833133526498328, -0.24892777483563822, 1.0509329068174003,

/* layer 2 */
-0.017641947937716403, -0.76847304571472597, -0.56744416413269716, 0.29879890755733857,
0.54582841656978143, -0.018611353229717905, -0.42216350381426643, 0.76166762458180848,

/* layer 3 */
-0.11318121712649422

};

static double NNCode04Weights[] =
{

/* layer 1 */
0.51060625451323394, -0.096389033700111801, -0.17778645542945556, 0.14561210007495079,
-0.068555991934721561, -0.049865930910817598, -0.18481673629921816, -0.13319863668650925,
0.88044640413584363, 0.098096972862446216, 0.19735084189391464, -0.0054493092603949654,
0.13494986417936716, 0.056982761122678055, 0.11510481499381627, 0.0057891229951390916,
-0.083361613931596093, 0.052053552428048364, -0.1553370625512345, 0.030165036081839347,
-0.28617821854581199, -0.11097827964990052, -0.57243142423311044, -0.047329173548563711,
-0.33135768737456606, -0.05162768471939827, 0.27327887430328363, -0.38664182307898842,
0.15659591438118173, 0.17529563864543207, -0.33311537274494829, -0.12389780494851717,
-0.32768177745012672, 0.069459943019016687, -0.22209762917288242, -0.24645336091834091,
0.28354481487959021, -0.035207155042198464, -0.32648966223034048, 0.061880858354739839,
-0.4869855866736722, -0.10074301317253678, 0.49363738276409419, -0.2565055762037321,
-0.63802414984326883, -0.12381706903449943, -0.014448611302640571, 0.063939081144100379,
0.23669355726989713, -0.40965973560080776, 0.16957035568109882, 0.15222444481595024,
-0.075159431385831491, 0.05589113625241704, -0.028474614489935799, -0.082345470608301621,
-0.047651654257849577, -0.042377502363725859, 0.14154177445032876, -0.40509615080556821,

/* layer 2 */
-1.1496821304724378, -0.33605321836949276, 1.3681328506936485, 0.054662417260536451,
-0.97384586768209647, 1.2858717271653068, 0.58624472586890075, 1.5079479450707438,
0.49640316604337115, 1.5468008817731342, -0.29556467429705929, 1.0073645849235378,
-0.73031197001668013, -0.57118263507806488, 0.46463117709032548,
1.4672565288686636, 0.83257617228180802, -1.0942364682012773, 0.001473387804507668,
1.4187515036847413, 1.3831857774864091, -0.65055742227438129, 1.4602976837868558,
1.3822044594723624, 1.119503671790125, -1.3896036866108439, -0.56973832792369306,
0.75762270373456986, 0.39338072964613247, -0.89076623600263349,
0.80854895300048102, 0.46657463972681901, -0.8140298814120891, -0.012094909634797568,
-1.1154133704916798, 1.0839781356076086, -0.73446657735186982, 0.98199786504969533,
-1.2369594326020987, 1.1254768546716032, 1.1619977668930461, 0.74126862371875202,
-1.0110999915548509, -0.6070322702789801, -0.97819324493034343,
1.355789633173256, 0.60082270723751952, 0.23904456225267842, 0.11994143700383661,
1.2084396256091481, -0.90729398030064945, -0.55536247238694247, -1.3481382609713886,
-0.91113493931786538, 1.3755713797809512, 1.4713310499677681, -1.0158928683184314,
0.01305227431770915, 0.046409351572033075, 1.2762213878320927,
1.4696754548998514, 1.4200747543109984, 1.4962405667980032, 0.37067238056947049,
1.4117772749701449, -0.99879530896358182, 0.9529051923415951, -1.0538071989211228,
1.4131793547139964, 1.1455379651458033, -1.1831633406959396, -0.80963145321422281,
-0.4414215010395981, 0.74524330383421911, -0.87235467314597304,
0.93354850343987172, -0.60572499708113092, 1.3943312636230332, 0.64848975792815033,
1.2728548505525628, -1.0488455983898337, -1.0291089944086109, 1.4424689697650896,
-1.2714742888291792, 0.53585231687600321, -0.95349313274564818, -1.25904961125868,
-0.56549255274519861, -0.65588704031388056, -1.5030070397408604,
-1.1679920355764324, 0.83701883637825414, 1.2995458953049737, 0.027013767977338215,
1.4048426358418773, -0.32418986048547055, 0.4574334683932581, 1.1962411467705725,
1.2665436784513338, 1.2657411256960591, 1.2409676643564984, -1.4620912344986778,
-0.78387105558161152, -0.73666287885516224, -0.015055615239760928,
-1.0629929936130729, 1.065758694241238, -1.0738341645441078, -0.073191103764941576,
0.98785419431978305, 1.277423049521049, 0.87455133918418859, 1.3753359484851913,
1.2950249187852954, 1.315532616612646, -0.7697772891349135, 1.4592768727538579,
-1.0143924226441157, 0.3160039890732354, -1.3653162848028435,

/* layer 3 */
0.66528045224269727, -1.1866093564505011, 0.1728327392315879, -1.4641165442529678,
1.2726534843472159, 0.52058766185963545, -1.2595966331497781, 1.2782654759386534

};

static double NNCode04Acts[56];

/* ---------------------------------------------------------- */
/*
  NNCode04Run - run neural network NNCode04

  inputs - the input variables of this network.
  The variable names are listed below, together with each
  variable's offset in the data set at the time code was
  generated (if the variable is then available).
  Variable (Offset)
  Liquid Kinematic Viscosity @ 210°F_MA (22)
  Octane Number, Motor, Clear_MA (33)
  Lower Flammability Limit_MA (37)
  Upper Flammability Limit_MA (38)

*/
/* ---------------------------------------------------------- */

void NNCode04Run( double inputs[], double outputs[], int outputType )
{
  int i, j, k, u;
  double *w = NNCode04Weights, *t = NNCode04Thresholds;

  /* Process inputs - apply pre-processing to each input in turn,
   * storing results in the neuron activations array.
   */

  /* Input 0: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[0] == -9999 )
    NNCode04Acts[0] = 0.19303747477298058;
  else
    NNCode04Acts[0] = inputs[0] * 0.7313232352069875 + 0.19196383444540677;

  /* Input 1: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[1] == -9999 )
    NNCode04Acts[1] = 0.72546684725025523;
  else
    NNCode04Acts[1] = inputs[1] * 0.0062656040341571764 + 0.72299602812157371;

  /* Input 2: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[2] == -9999 )
    NNCode04Acts[2] = 0.11220237698870322;
  else
    NNCode04Acts[2] = inputs[2] * 0.14925373134328357 + 0.11208987955223881;

  /* Input 3: standard numeric pre-processing: linear shift and scale. */
  if ( inputs[3] == -9999 )
    NNCode04Acts[3] = 0.16838051583079791;
  else
    NNCode04Acts[3] = inputs[3] * 0.023900573613195492 + 0.16840902654951223;

  /*
   * Process layer 1.
   */

  /* For each unit in turn */
  for ( u=0; u < 15; ++u )
  {
    /*
     * First, calculate post-synaptic potentials, storing
     * these in the NNCode04Acts array.
     */

    /* Initialise hidden unit activation to zero */
    NNCode04Acts[4+u] = 0.0;

    /* Accumulate weighted sum from inputs */
    for ( i=0; i < 4; ++i )
      NNCode04Acts[4+u] += *w++ * NNCode04Acts[0+i];

    /* Subtract threshold */
    NNCode04Acts[4+u] -= *t++;

    /* Now apply the hyperbolic activation function, ( e^x - e^-x ) / ( e^x + e^-x ).
     * Deal with overflow and underflow
     */
    if ( NNCode04Acts[4+u] > 100.0 )
       NNCode04Acts[4+u] = 1.0;
    else if ( NNCode04Acts[4+u] < -100.0 )
      NNCode04Acts[4+u] = -1.0;
    else
    {
      double e1 = exp( NNCode04Acts[4+u] ), e2 = exp( -NNCode04Acts[4+u] );
      NNCode04Acts[4+u] = ( e1 - e2 ) / ( e1 + e2 );
    }
  }

  /*
   * Process layer 2.
   */

  /* For each unit in turn */
  for ( u=0; u < 8; ++u )
  {
    /*
     * First, calculate post-synaptic potentials, storing
     * these in the NNCode04Acts array.
     */

    /* Initialise hidden unit activation to zero */
    NNCode04Acts[19+u] = 0.0;

    /* Accumulate weighted sum from inputs */
    for ( i=0; i < 15; ++i )
      NNCode04Acts[19+u] += *w++ * NNCode04Acts[4+i];

    /* Subtract threshold */
    NNCode04Acts[19+u] -= *t++;

    /* Now apply the hyperbolic activation function, ( e^x - e^-x ) / ( e^x + e^-x ).
     * Deal with overflow and underflow
     */
    if ( NNCode04Acts[19+u] > 100.0 )
       NNCode04Acts[19+u] = 1.0;
    else if ( NNCode04Acts[19+u] < -100.0 )
      NNCode04Acts[19+u] = -1.0;
    else
    {
      double e1 = exp( NNCode04Acts[19+u] ), e2 = exp( -NNCode04Acts[19+u] );
      NNCode04Acts[19+u] = ( e1 - e2 ) / ( e1 + e2 );
    }
  }

  /*
   * Process layer 3.
   */

  /* For each unit in turn */
  for ( u=0; u < 1; ++u )
  {
    /*
     * First, calculate post-synaptic potentials, storing
     * these in the NNCode04Acts array.
     */

    /* Initialise hidden unit activation to zero */
    NNCode04Acts[27+u] = 0.0;

    /* Accumulate weighted sum from inputs */
    for ( i=0; i < 8; ++i )
      NNCode04Acts[27+u] += *w++ * NNCode04Acts[19+i];

    /* Subtract threshold */
    NNCode04Acts[27+u] -= *t++;

  }

  /* Type of output required - selected by outputType parameter */
  switch ( outputType )
  {
    /* The usual type is to generate the output variables */
    case 0:


      /* Post-process output 0, numeric linear scaling */
      outputs[0] = ( NNCode04Acts[27] - 0.20725388601036268 ) / 0.0051813471502590676;
      break;

    /* type 1 is activation of output neurons */
    case 1:
      for ( i=0; i < 1; ++i )
        outputs[i] = NNCode04Acts[27+i];
      break;

    /* type 2 is codebook vector of winning node (lowest actn) 1st hidden layer */
    case 2:
      {
        int winner=0;
        for ( i=1; i < 15; ++i )
          if ( NNCode04Acts[4+i] < NNCode04Acts[4+winner] )
            winner=i;

        for ( i=0; i < 4; ++i )
          outputs[i] = NNCode04Weights[4*winner+i];
      }
      break;

    /* type 3 indicates winning node (lowest actn) in 1st hidden layer */
    case 3:
      {
        int winner=0;
        for ( i=1; i < 15; ++i )
          if ( NNCode04Acts[4+i] < NNCode04Acts[4+winner] )
            winner=i;

        outputs[0] = winner;
      }
      break;
  }
}

/* ---------------------------------------------------------- */
/*
  NNCode04RunPadded - run model NNCode04

  inputs - the input variables, in the same number and order
  as in the data set at the time the code was generated.
  This alternative routine is useful if you want a consistent
  interface for your generated routines, so that the number
  and order of variables is the same for all of them.
  Variables (ones used as inputs marked thus *):
  0)	c0 = Prop.(Unit)
  1)	vij
  2)	f(vij)ref (REG)
  3)	Set
  4)	nºinsat_MA
  5)	Mole. Wt._MA
  6)	Normal Boiling Point_MA
  7)	Normal Freezing Point in air @ 1 atm_MA
  8)	Critical Temp._MA
  9)	Critical Pressure_MA
  10)	Critical Volume_MA
  11)	Critical Volume_MA1
  12)	Critical Comp. Factor_MA
  13)	Accentric Factor_MA
  14)	Specific Gravity 60/60_MA
  15)	API Gravity @ 60°F_MA
  16)	Liquid Density @ 60°F_MA
  17)	Refractive Index @ 77°F_MA
  18)	Vapor Pressure @ 100°F_MA
  19)	Ideal Gas Cp @ 60°F_MA
  20)	Liquid Cp @ 60°F_MA
  21)	Liquid Kinematic Viscosity @ 100°F_MA
  22)	Liquid Kinematic Viscosity @ 210°F_MA *
  23)	Heat of Vapor. @ Normal Boiling Point_MA
  24)	Liquid Heat of Combustion @ 77°F, Net_MA
  25)	Liquid Surface Tension @ 77°F_MA
  26)	Solubility Parameter_MA
  27)	Flash Point_MA
  28)	Ideal Gas Heat of Formation @ 77°F_MA
  29)	Ideal Gas Gibbs Free Energy of Formation @ 77°F_MA
  30)	Heat of Fusion @ 77°F_MA
  31)	Liquid Coefficient of Expansion @ 60°F_MA
  32)	Aniline Point_MA
  33)	Octane Number, Motor, Clear_MA *
  34)	Octane Number, Motor, +3 ml TEL/gal_MA
  35)	Octane Number, Research, Clear_MA
  36)	Octane Number, Research, +3 ml TEL/gal_MA
  37)	Lower Flammability Limit_MA *
  38)	Upper Flammability Limit_MA *

*/
/* ---------------------------------------------------------- */

void NNCode04RunPadded( double inputs[], double outputs[], int outputType )
{
  double in[4];

  /* Copy inputs */
  in[0]=inputs[22];
  in[1]=inputs[33];
  in[2]=inputs[37];
  in[3]=inputs[38];


  /* Run the network */
  NNCode04Run( in, outputs, outputType );
}


/*
  Test harness. Compile including this main() procedure, as
  a windows console program or a DOS program, to interactively
  test that the software functions as expected.
*/

void main(void)
{
  int i, outputType=0, noOutputs=1;
  double inputs[4], outputs[4];

  printf( "\n\nNNCode test harness program. Enter inputs below\n" );
  printf( "Nominal variables should be numbered starting at 1 (0 for missing)\n" );
  printf( "(e.g. if an input is Gender={male,female}, enter 1 for male, 2 for female)\n" );

  /* Infinite (user-breakable) loop for repeated tests */
start_of_loop:
  while ( 1 )
  {
    /* Get the input pattern */
    for ( i=0; i < 4; ++i )
    {
      printf( "Enter value for input %d: ", i+1 );
      scanf( "%lg", & inputs[i] );

      /* Check for sub-menu */
      if ( inputs[i] == MENUCODE )
      {
        printf( "Control menu. Select output style, or exit:\n" );
        printf( "0. Normal output style (output variable)\n" );
        printf( "1. Output layer activations\n" );
        printf( "2. Codebook vector (usual only for Kohonen networks\n" );
        printf( "3. Winning hidden neuron (ditto only Kohonen)\n" );
        printf( "4. Exit program\n" );
        printf( "> " );
        scanf( "%d", & outputType );
        if ( outputType < 0 || outputType > 3 )
        {
          printf( "\nBye.\n" );
          return;
        }
        else
        {
          /* Determine how many outputs there are to display (depends on
           * output type)
           */
          switch ( outputType )
          {
            case 0:
              noOutputs = 1;
              break;

            case 1:
              noOutputs = 1;
              break;

            case 2:
              noOutputs = 4;
              break;

            case 3:
              noOutputs = 1;
              break;
          }
          goto start_of_loop;
        }
      }
    }

    /* Run the neural network */
    NNCode04Run( inputs, outputs, outputType );

    /* Display the output of the neural network */
    printf( "\n\nOutput of neural network:\n" );

    for ( i=0; i < noOutputs; ++i )
    {
      printf( "Output %d: ", i+1 );
      printf( "%g\n", outputs[i] );
    }

    printf( "\nEnter next input pattern (for control menu inc. exit, enter %d for any input):\n", MENUCODE );
  }
}
